### ISSUE TITLE
Problem: check how easy it is to let our indexer to work against CosmosHub (Gaia) network

### ISSUE THREAD

**Issue by ysong42** [crypto-com/chain-indexing#588]

**Comment by ysong42** [comment]
## Findings

Our indexing could pull and parse data from CosmosHub after some changes in the code.

## Changes

### Config

``` TOML
[blockchain]
bonding_denom = "uatom"
account_address_prefix = "cosmos"
account_pubkey_prefix = "cosmospub"
validator_address_prefix = "cosmosvaloper"
validator_pubkey_prefix = "cosmosvaloperpub"
connode_address_prefix = "cosmosvalcons"
connode_pubkey_prefix = "cosmosvalconspub"

[tendermint]
http_rpc_url = "PLEASE_ASK_DEVOPS_TEAM_TO_GET_THE_URL:26657"
insecure = true
# When enabled, genssi parsing will reject any non-Cosmos SDK built-in module
# inside genesis file.
strict_genesis_parsing = false

[cosmosapp]
http_rpc_url = "PLEASE_ASK_DEVOPS_TEAM_TO_GET_THE_URL:1317"
insecure = true

[http]
cors_allowed_origins = ["*"] # Optional, if you want to test it through Explorer, then add the "*"

[projection]
enables = [
    "AccountMessage",
    "Block",
    "Transaction",
    "Validator",
    "BlockEvent",
    "Proposal",
]
```

### Code

1. Disable the APY calculation in handler, as some APIs on CosmosHub is not available. 
 
`infrastructure/httpapi/handlers/validators.go`. Around line 176.

``` go
	handler.globalAPY = big.NewFloat(0)
	// if handler.globalAPYLastUpdatedAt.Add(1 * time.Hour).Before(time.Now()) {
	// 	handler.logger.Info("going to fetch latest global APY")
	// 	handler.globalAPY, err = handler.getGlobalAPY()
	// 	if err != nil {
	// 		handler.logger.Errorf("error getting global APY: %v", err)
	// 		httpapi.InternalServerError(ctx)
	// 		return
	// 	}
	// 	handler.globalAPYLastUpdatedAt = time.Now()
	// }
```

Change the hard-code genesis height from `0` to `5200790`. 

`bootstrap/syncmanager.go`, around line 120 and line 182.

```
// func (manager *SyncManager) SyncBlocks(latestHeight int64, isRetry bool) error {
...
	// if none of the block has been indexed before, start with 5200790
	currentIndexingHeight := int64(5200790)
	if maybeLastIndexedHeight != nil {
		currentIndexingHeight = *maybeLastIndexedHeight + 1
	}
...
// func (manager *SyncManager) syncBlockWorker(blockHeight int64) ([]command_entity.Command, error) {
...
	if blockHeight == int64(5200790) {
		genesis, err := manager.client.Genesis()
		if err != nil {
			return nil, fmt.Errorf("error requesting chain genesis: %v", err)
		}

		return parser.ParseGenesisCommands(genesis, manager.accountAddressPrefix)
	}
...
```

## Good to run

Now compile the new binary and run it, you should be able to see the projections are catching up the block through DB. 🚀 

Notes: the first time to run it, please set the `config.sync.window_size` to be a small number, like `1`. The genesis file is very big (around 14MB). `window_size` too big may kill the server and put a heavy load on the CosmosHub node. After running for a while, you could stop it and change it to a bigger `window_size`.
